### ISSUE TITLE
How to make authenticated method calls and subscriptions?

### ISSUE THREAD

**Issue by brylie** [tanutapi/dart_meteor#1]
Is there any documentation showing how to register/authenticate a user via Meteor Accounts and then make authenticated method calls and subscriptions?

**Comment by tanutapi** [comment]
You can basically call a login function.

meteor.loginWithPassword(username, password, delayOnLoginErrorSecond: 10);

Then all method calls and subscriptions on your session will base on that user account.

**Comment by tanutapi** [comment]
Hi @brylie 

Please have a look at
https://medium.com/@tanutapi/writing-flutter-mobile-application-with-meteor-backend-643d2c1947d0?sk=52ce2fa2603934e7395e2d19dd54e06c

**Comment by brylie** [comment]
Very cool! Thsnks for the writeup.
