### ISSUE TITLE
latest version 1.1.1 can't install

### ISSUE THREAD

**Issue by YouSour** [tanutapi/dart_meteor#11]
hi , i try to add your package (latest version : 1.1.1) then suddenly error come out , what should i do ? update crypto package ? and how to update it ? thank in advance 😄 

---error message --- 
[mobile_core] flutter pub get
Running "flutter pub get" in mobile_core...                     
Because every version of flutter_test from sdk depends on crypto 2.1.4 and dart_meteor >=1.1.0 depends on crypto ^2.1.5, flutter_test from sdk is incompatible with dart_meteor >=1.1.0.

So, because mobile_core depends on both dart_meteor ^1.1.1 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because mobile_core depends on both dart_meteor ^1.1.1 and flutter_test any from sdk, version solving failed.)
exit code 1  
---------------------
More Info : my flutter version : v 1.17.5  & dart 2.8.4

**Comment by tanutapi** [comment]
Thank you for report it. I found that I have to update crypto package version down to 2.1.4.

**Comment by tanutapi** [comment]
I just published 1.1.2 to pub.dev. Please check.

**Comment by YouSour** [comment]
that's ok , bro good job :smile:
