### ISSUE TITLE
extract or reusable MeteorClient class

### ISSUE THREAD

**Issue by YouSour** [tanutapi/dart_meteor#12]
what should i do if i don't want declare this again and again in my app 🤔  i want to copy this code to one file when i want to use it i can import it 
```import 'package:dart_meteor/dart_meteor.dart';```
```MeteorClient meteor = MeteorClient.connect(url: 'https://yourdomain.com'); ```

**Comment by tanutapi** [comment]
I usually declare it one in the global level at /lib/main.dart. Then I can access the instance of it from anywhere. Please see the example project.

**Comment by YouSour** [comment]
yeah , i do it too, bro @tanutapi but i get some error from >>>MeteorError isn't define<<< with Meteor.loginwithpassword() 
```
  meteor.loginWithPassword(_username, _password)
                                    .then((value) {
                                  print(value);
                                  Routes.sailor.navigate('/home',
                                      params: {'username': "you sour"});
                                }).catchError((err) {
                                  if (err is MeteorError) {
                                      print(err);
                                });
```

**Comment by tanutapi** [comment]
In main.lib

```
import 'package:dart_meteor/dart_meteor.dart';
MeteorClient meteor = MeteorClient.connect(url: 'https://yourdomain.com');
```

In another file, you still need to import the dart_meteor package together with your main.dart to access your meteor instance.
```
import 'package:dart_meteor/dart_meteor.dart';
import 'package:your_app/main.dart';
...
void someFunction() {
  meteor.loginWithPassword(...);
}
```

**Comment by YouSour** [comment]
ok , thank you , bro , i got it @tanutapi
