### ISSUE TITLE
Passing param to subscription

### ISSUE THREAD

**Issue by SuMitVayuz** [tanutapi/dart_meteor#19]
Hi there! 
Meteor.subscribe("fetch_all_notifications", user_id);
This is the subscription in meteor, I'm passing user id because I only need notifications for a particular id.

Meteor.client.subscribe("fetch_all_notifications", [ ]);
But how can I pass a string in this param parameter? When I try passing a value, I no longer receive the data.

Is there any way to achieve it? There should be a way right?

**Comment by tanutapi** [comment]
You can pass the parameter as:

'''
meteorClient.subscribe('fetch_all_notifications', [ userId ]);
'''

And if you have a look in debugging console, you should see the data sent back to you.

**Comment by SuMitVayuz** [comment]
Thanks, bro, the problem was that the notification subscription was only returning new notification, and the user_id I was using didn't have any notification.
