### ISSUE TITLE
Allow users to `loginWithPassword` using email address

### ISSUE THREAD

**Issue by vladbalan** [tanutapi/dart_meteor#2]
Hey @tanutapi, thanks for this fantastic package! 

Currently, `loginWithPassword` only accepts a `username` and a `password`. It would be great if this functionality was extended to also accept email addresses. I think replacing `'user': {'username': user},` on line 398 with simply `'user': user,` should do the trick. Was there a reason for restricting login access to only accept usernames? 

I would be happy to create a PR for this myself, if you like.

**Comment by tanutapi** [comment]
Sorry for lately reply. PR is welcome!

**Comment by tanutapi** [comment]
Commit e436d99047e63012f571c1182def121e2540a841 allows passing either email and password to loginWithPassword.

**Comment by sky5media** [comment]
`var selector;
    if (!user.contains('@')) {
      selector = {'email': user};
    } else {
      selector = {'username': user};
    }`
Should it be otherwise, like:
`    var selector;
    if (user.contains('@')) {
      selector = {'email': user};
    } else {
      selector = {'username': user};
    }`

otherwise I am getting 403 while trying to login with email

**Comment by tanutapi** [comment]
I am so sorry. I should invest more tests on this package. The new release is out.

**Comment by sky5media** [comment]
Thank you for quick fix!

**Comment by vladbalan** [comment]
Thank you @tanutapi!
