### ISSUE TITLE
disable debug mode

### ISSUE THREAD

**Issue by YouSour** [tanutapi/dart_meteor#25]
hi , bro @tanutapi , i would like to know how can i disable debug mode ? thank in advance 😄

**Comment by tanutapi** [comment]
You have to make a modification into the beginning of `dart_meteor/lib/src/ddp_client.dart`. Set the `const debug = false`.

**Comment by YouSour** [comment]
@tanutapi i think you should add an optional param to MeteorClient.connect(url: '' ,debug: false) that allow to set debug true or false maybe good 😄 what do you think ?

**Comment by tanutapi** [comment]
Now you have it in 2.0.0
`MeteorClient.connect({required String url, bool debug = false})`

**Comment by YouSour** [comment]
@tanutapi noted , bro
