### ISSUE TITLE
Meteor 2.3 can't connect,but meteor 1.8 is on,I don't know why I

### ISSUE THREAD

**Issue by xiaodusx1** [tanutapi/dart_meteor#34]

**Comment by xiaodusx1** [comment]
flutter: MeteorClient[310452645] - Make a connection to ws://127.0.0.1:3000/websocket

flutter: connected: false, status: DdpConnectionStatusValues.connecting, retryCount: 0, retryTime: 0:00:00.000000, reason: null

**Comment by tanutapi** [comment]
I just fixed the issues. Please check on the new release 2.0.2.

**Comment by keepjhonnying** [comment]
I LOVE YOU @tanutapi

**Comment by xiaodusx1** [comment]
Yes,it's OK now

**Comment by xiaodusx1** [comment]
Thank you so much.
