### ISSUE TITLE
meteor.logout() has something wrong like this:[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by xiaodusx1** [tanutapi/dart_meteor#35]

**Comment by xiaodusx1** [comment]
Latest edition both meteor and flutter.

**Comment by tanutapi** [comment]
Could you share a snippet of your code?

**Comment by xiaodusx1** [comment]
Like this:

onPressed: () {
                          meteor.logout();
                        },

**Comment by tanutapi** [comment]
I just fixed the issues. Please check on the new release 2.0.2.

**Comment by xiaodusx1** [comment]
It's work,but don't have any callback

**Comment by tanutapi** [comment]
The `logout` function itself return a Future. So you can use async/await together with try-catch to know that the logging out is succeeded or not.

```
onPress: () async {
  try {
    await meteor.logout();
    print('Logout done');
  } catch (e) {
    print('Error occurs $e');
  }
}
```

**Comment by xiaodusx1** [comment]
No meteor servers callback,and it won't clear up the local login data.
