### ISSUE TITLE
check subscribe is ready

### ISSUE THREAD

**Issue by YouSour** [tanutapi/dart_meteor#4]
hi , how can i check meteor.subscribe() is ready or not ? i want to know it works or not
```
class YourWidget extends StatefulWidget {
  YourWidget() {}

  @override
  _YourWidgetState createState() => _YourWidgetState();
}

class _YourWidgetState extends State<YourWidget> {
  SubscriptionHandler _subscriptionHandler;

  @override
  void initState() {
    super.initState();
    meteor.prepareCollection('customers');
    _subscriptionHandler = meteor.subscribe('customers', []);
  }

  @override
  void dispose() {
    super.dispose();
    _subscriptionHandler.stop();
  }
}
```

**Comment by tanutapi** [comment]
Passing `onReady` to meteor.subscribe() should let you know when your subscription is ready.

```
meteor.subscribe(
  'customers',
  [],
  onReady: () {
    // Your code here
  },
);
```

I have no test on this please tell me if it works or not.

**Comment by YouSour** [comment]
@tanutapi i can't get anything from onReady() , what's problem ? :(
```
meteor.subscribe('messages', [], onReady: () {
      print('ready !!!!');
    });
```

**Comment by YouSour** [comment]
can you check my source code here : [https://drive.google.com/file/d/1N8zYubxoyfRWplR-hoHDZyM49NruzeYv/view?usp=sharing](url) (Front End) and here (Back End) [https://github.com/tanutapi/simple-meteor-chat](url)

**Comment by tanutapi** [comment]
I just confirm with a new test that onReady should be called correctly. You can see it in the latest test log. (https://github.com/tanutapi/dart_meteor/runs/709924502?check_suite_focus=true)
```
DDP[562026231] - 2020-05-26 15:45:17.234528
DDP[562026231] - Recv: {"msg":"ready","subs":["messages-fTwFqoM8_ThgehO7m9fIqA=="]}
onReady is called.
...
00:11 +5: All tests passed!  
```
In the test file:
```
    test('meteor.subscribe with onReady', () async {
      var completer = Completer();
      expect(completer.future, completion(true));
      await meteor.subscribe(
        'messages',
        [],
        onReady: () {
          print('onReady is called.');
          completer.complete(true);
        },
      );
      await Future.delayed(Duration(seconds: 5));
      if (!completer.isCompleted) {
        completer.complete(false);
      }
    });
```

P.S. I cannot access your code right now. Tomorrow I will try to have a look again.

**Comment by YouSour** [comment]
@tanutapi ok, i wait for your answer , right now i try to find the problem , too , don't know why i can't get anything from collection that i subscribe 😄

**Comment by tanutapi** [comment]
You make a subscription too early. The connection to the DDP server is not done yet. The simple solution is to wrap it in meteor.startup(). Or in the real application, you should have a "connecting page" shows up while the meteor trying to make a connection to your server and move to another page when the connection is ready.

```
  void initState() {
    super.initState();
    meteor.prepareCollection('messages');
    meteor.startup(() {
      _subscriptionHandler = meteor.subscribe('messages', [], onReady: () {
        print('ready to go !!!');
      });
    });
  }
```

**Comment by YouSour** [comment]
thank you so much 😄  i can start my real project now , keep it up , bro, good job @tanutapi
