### ISSUE TITLE
Error with DateTime type

### ISSUE THREAD

**Issue by X-SLAYER** [tanutapi/dart_meteor#43]
hello when i try to pass datetime type in args list i got this exception

```Converting object to an encodable object failed: Instance of 'DateTime```

**Comment by X-SLAYER** [comment]
worked for me when i converted the dateTime toIso8601String

**Comment by X-SLAYER** [comment]
Still Not working sorry even after i updated the package

**Comment by tanutapi** [comment]
Hi @X-SLAYER 

I found that there is a bug on escaping the DateTime before sending out to Meteor server. I will commit the fix soon. Please help me check that it fixes your problem.

**Comment by tanutapi** [comment]
A new version 2.1.0 is now released.
