### ISSUE TITLE
Web support in master branch

### ISSUE THREAD

**Issue by AugustoResende** [tanutapi/dart_meteor#47]
https://pub.dev/packages/universal_io

**Comment by tanutapi** [comment]
Hi! Thank you for your suggestion. I will try it!

**Comment by tanutapi** [comment]
Sadly, I found that most of the `websocket` in `universal_io` is not implemented. They point out to `web_socket_channel` package which I need help from somebody to try it.

**Comment by YouSour** [comment]
+1

**Comment by tanutapi** [comment]
For more information on supporting the web platform in the master branch, please see: https://github.com/tanutapi/dart_meteor/pull/64
