### ISSUE TITLE
FindOne , Find Feature

### ISSUE THREAD

**Issue by Saeeed-B** [tanutapi/dart_meteor#53]
@tanutapi 
Hello
Can we directly receive a specific data based on its ID?
With findOne ,

This feature is implemented in this package.
[https://github.com/ShivamArora/meteorify#get-subscribed-datacollection](https://github.com/ShivamArora/meteorify#get-subscribed-datacollection)

**Comment by tanutapi** [comment]
Your meteor instance, meteor, has .collection('collectionName').
You can use:

```
try {
  var user = meteor.collection('users').where((user) => user['_id'] == 'YOUR_USER_ID').first;
} catch (err) {
  // Not found!
}
```
