### ISSUE TITLE
Meteor server code for running tests

### ISSUE THREAD

**Issue by bolaum** [tanutapi/dart_meteor#8]
Hey @tanutapi, I noticed after the PR that you have some tests implemented. Where can I find the code for the meteor server that implements the methods called by the tests? Maybe I can help improve the test cases.

Since we intend to use this lib extensively for our new project, we intend to collaborate with it often. Is there a way to contact you directly so we can discuss some things related to the code? If you are interested, you can DM me at @bolaum on twitter so we can find better ways to keep in touch privately. 

Thanks.

**Comment by tanutapi** [comment]
Hi @bolaum, I run the test against https://github.com/tanutapi/simple-meteor-chat. If you have a look at https://github.com/tanutapi/dart_meteor/blob/master/.github/workflows/dart.yml, you will see that I spin up simple-meteor-chat as a docker container.
